FROM node:13.7.0

# Create app directory
WORKDIR /app

# Install app dependencies
COPY ./package.json .
RUN npm install

# Bundle app source
COPY ./ ./

# Create client build;
RUN npm run build

# Start the app
CMD ["npm", "run", "start"]
#CMD [ "/bin/bash" ]

# Expose ports
EXPOSE 8000
