FROM node:13.7.0 as builder

# Create app directory
WORKDIR /app

# Install app dependencies
COPY ./package.json ./

# Bundle app source
COPY . .

RUN npm run build

# Start the app
CMD [ "npm", "start" ]
#CMD [ "/bin/bash" ]

FROM nginx
# Expose ports
EXPOSE 8000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
