version: '3.6' # aim to deploy in swarm
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - .env
    volumes:
      - /app/node_modules 
      - ./server:/app 
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8000:80"