version: '3.6'
services:
  nginx:
    restart: always
    build:
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
  api:
    build:
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - APPID=0839abe5cdaa810229327c000cba070d
      - MAP_ENDPOINT=http://api.openweathermap.org/data/2.5
      - TARGET_CITY=Helsinki
  client:
    build:
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app 
  #tests:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.dev
  #    dockerfile: Dockerfile
  #  volumes:
  #    - /app/node_modules
  #    - .:/app
  #  command: ["npm", "run", "test"]