version: '3.6' # aim to deploy in swarm
services:
  approot:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules 
      - ./:/app 
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - .env
    volumes:
      - ./server:/app 
    ports:
      - "5000:5000"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"