version: '3.6'
services:
  api:
    build:
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./server
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app 
  nginx:
    restart: always
    build:
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"
  #tests:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.dev
  #    dockerfile: Dockerfile
  #  volumes:
  #    - /app/node_modules
  #    - .:/app
  #  command: ["npm", "run", "test"]