version: '3.6' # aim to deploy in swarm
services:
    # Setup frontend (client) container 
    client:
        #container_name: weatherapp_frontend
        image:  weatherapp_frontend:latest
        build:
            dockerfile: Dockerfile
            context: ./client
        #command: npm start
        environment:
            ENDPOINT: "http://api.openweathermap.org/data/2.5"
        #working_dir: /usr/src/weatherapp_frontend
        ports:
            - "8000:8000"
        volumes:
            - ./frontend/src:/usr/src/app/src
        depends_on:
            - server

    # Setup backend (server-side) container
    server:
        #container_name: weatherapp_backend
        image: weatherapp_backend:latest
        build:
            dockerfile: Dockerfile
            context: ./
        command: npm run dev
        environment:
            APIkey: "0839abe5cdaa810229327c000cba070d" #OpenWeatherMap APIkey
            MAP_ENDPOINT: "http://api.openweathermap.org/data/2.5/weather" #overwrite default settings
            TARGET_CITY: "Helsinki,fi" #overwrite default settings
        ports:
            - "9000:9000"
        #working_dir: /usr/src/weatherapp_backend
        volumes:
            - ./backend/src:/usr/src/app/src
            #- ./:/usr/src/weatherapp_backend