version: 2.6
jobs:
  build:
    docker:
      - image: circleci/node:13.7.0
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm build
  test:
    docker:
      - image: circleci/node:13.7.0
    steps:
      - checkout
      - run: npm install
      #- run: npm run test
  hithere:
    docker:
      - image: circleci/node:13.7.0
    steps:
      - checkout
      - run: echo "katso sää!"
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere