FROM node:13.7.0

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install app dependencies
COPY ./package.json ./
RUN npm install

# Bundle app source
COPY . .

#EXPOSE 5000

CMD ["npm", "run", "dev"]